name: Shopify Sync Alternative

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests python-dotenv

      - name: Run sync
        run: python sync.py
        env:
          SUPPLIER_API_URL: ${{ secrets.SUPPLIER_API_URL }}
          SUPPLIER_TOKEN: ${{ secrets.SUPPLIER_TOKEN }}
          SHOPIFY_API_KEY: ${{ secrets.SHOPIFY_API_KEY }}
          SHOPIFY_PASSWORD: ${{ secrets.SHOPIFY_PASSWORD }}
          SHOPIFY_STORE: cgdboutique
