name: Sync Supplier Products

on:
  workflow_dispatch:   # lets you run manually from GitHub

jobs:
  run-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run sync script
        env:
          SUPPLIER_TOKEN: ${{ secrets.SUPPLIER_TOKEN }}
          SHOPIFY_TOKEN: ${{ secrets.SHOPIFY_TOKEN }}
        run: python sync.py
